version: '3.8'

services:
  # Gotenberg - PDF Generator Service (Production)
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg-pdf-service-prod
    restart: unless-stopped
    ports:
      - "3000:3000"  # Expose to public for production
    environment:
      - CHROMIUM_DISABLE_WEB_SECURITY=true
      - CHROMIUM_ALLOW_LIST=file:///tmp/.*
      - GOTENBERG_LOG_LEVEL=info
      - GOTENBERG_WEBHOOK_URL=  # Optional: webhook for notifications
    # Security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    # Resource limits (increased for production)
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx Reverse Proxy (Optional but recommended)
  nginx:
    image: nginx:alpine
    container_name: gotenberg-nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - gotenberg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    name: gotenberg-production-network
    driver: bridge
