[build]
builder = "dockerfile"

[deploy]
startCommand = "gotenberg"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
CHROMIUM_DISABLE_WEB_SECURITY = "true"
CHROMIUM_ALLOW_LIST = "file:///tmp/.*"
GOTENBERG_LOG_LEVEL = "info"
